# Use root/example as user/password credentials
version: '3.1'

services:
  frontend:
    image: gomiboStock/frontend
    build:
      context: ./frontend

    ports:
      - 80:80 # default port
      - 443:443 # ssl port
  db:
    image: mysql
    environment: # Configuration of the database server as specified in their README
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD?:}
      MYSQL_DATABASE: ${DATABASE_NAME?:}
      MYSQL_USER: ${DATABASE_USER?:}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD?:}
    volumes:
      # We store the database files in ./data/db in our repository
      - ./data/db:/var/lib/mysql
      # We mount the SQL dump files in ./data/sql to automatically seed the database
      - "./data/sql:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: gomiboStock/backend
    build:
      context: ./backend/
