version: '3.9'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:?}:80"

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:?}:80"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${DATABASE_NAME:?}"
      MYSQL_USER: "${DATABASE_USER:?}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD:?}"
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - ./database/data/db:/var/lib/mysql
      - ./database/data/sql:/docker-entrypoint-initdb.d
